name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # or 'main', use your actual branch name

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: hackhunt-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t joannjoseph23/hackhunt-frontend:latest .

      - name: Push Docker image
        run: docker push joannjoseph23/hackhunt-frontend:latest
